### ISSUE TITLE
error

### ISSUE THREAD

**Issue by athulaugustine** [iSysLab/sketch2html#1]
[2019-02-13 15:18:36,399] ERROR in app: Exception on /send_img [POST]
Traceback (most recent call last):
  File "C:\Users\AT\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\AT\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\AT\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\AT\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\AT\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\AT\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 52, in send_img
    layoutDetection.main("images/origin.jpg", html_filename, html_filename)
  File "C:\Users\AT\Desktop\sketch2html-master\layoutDetection.py", line 782, in main
    html.startHtml(htmlFileName, cssFileName)
  File "C:\Users\AT\Desktop\sketch2html-master\layoutDetection.py", line 248, in startHtml
    self.f.append(open("html/" + html + ".html", "w"))
FileNotFoundError: [Errno 2] No such file or directory: 'html/sketch2html_result_1550051315869.html'
127.0.0.1 - - [13/Feb/2019 15:18:36] "[1m[35mPOST /send_img HTTP/1.1[0m" 500 -

**Comment by VivekSaurabhVerma** [comment]
@athulaugustine were you able to resolve the issue?
