### ISSUE TITLE
Error after clicking on Send to Server

### ISSUE THREAD

**Issue by proshikari** [iSysLab/sketch2html#2]
[2019-11-05 03:49:21,013] ERROR in app: Exception on /send_img [POST]
Traceback (most recent call last):
  File "C:\Users\Ganesh\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Ganesh\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Ganesh\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Ganesh\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Ganesh\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Ganesh\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 52, in send_img
    layoutDetection.main("images/origin.jpg", html_filename, html_filename)
  File "C:\Users\Ganesh\Downloads\sketch2html-master\layoutDetection.py", line 770, in main
    merged_lines_all = lineMerge.mergeLine(img, lines)
  File "C:\Users\Ganesh\Downloads\sketch2html-master\layoutDetection.py", line 144, in mergeLine
    for line in self.get_lines(lines):
  File "C:\Users\Ganesh\Downloads\sketch2html-master\layoutDetection.py", line 15, in get_lines
    return [l[0] for l in lines_in]
TypeError: 'NoneType' object is not iterable
127.0.0.1 - - [05/Nov/2019 03:49:21] "[1m[35mPOST /send_img HTTP/1.1[0m" 500 -

**Comment by GTron-1729** [comment]
@proshikari @jyheo @qkek984 @psm9733  I am also getting a blank screen after passing an image as input and there is an error message in the console log. So anyone solved the issue please help Guys!
